name 'cesnet-kerberos'
version '1.1.1'
source 'https://github.com/MetaCenterCloudPuppet/cesnet-kerberos'
author 'Frantisek Dvorak <valtri@civ.zcu.cz>'
license 'MIT'
summary 'MIT Kerberos'
description 'MIT Kerberos server and client'
project_page 'https://github.com/MetaCenterCloudPuppet/cesnet-kerberos'

dependency 'puppetlabs/stdlib', '>= 1.0.0 <5.0.0'
